language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang
    - os: windows
      compiler: gcc
      before_install:
        - choco install cygwin
        - C:\\tools\\cygwin\\cygwinsetup.exe -q -P autoconf,make

script:
  - ./autogen.sh #run autoconf to generate configure script based on platform features
  - ./configure #run generated configure script, which in turn will generate a platform-specific Makefile
  - make #build the project using the generated Makefile
  - make check #run unit tests
