language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang
#    - os: windows
#      compiler: gcc

script:
  - mkdir -p build #create the directory to store the build in
  - cd build #navigate into the directory
  - cmake .. #invoke CMake, placing the build in the build directory
  - make
  - make test
